version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
  open-pull-requests-limit: 99
  rebase-strategy: disabled
  ignore:
    - dependency-name: "com.fasterxml.jackson.core:*"
      update-types: [ "version-update:semver-minor" ]
