sudo: required
dist: trusty
language: java

services:
  - docker

jdk:
 - oraclejdk7

env:
  matrix:
    - DOCKER_VERSION="1.11.2"
    - DOCKER_VERSION="1.10.3"

before_install:
  - pip install --user codecov
  - docker info
  - docker version
  - ./get-docker-com.sh
  - ./travis-before-install.sh

script: mvn test

after_success:
  - ./travis-after-success.sh

after_script:
  - sudo cat /var/log/upstart/docker.log
