sudo: required
dist: trusty
language: java

services:
  - docker

jdk:
 - oraclejdk7

env:
  matrix:
    - DIND_IMAGE=kostyasha/dind:fedora23-1.11
#      DOCKER_DAEMON_ARGS="-D"

before_install:
  - ./travis-before-install.sh

script: mvn test

after_success:
  - ./travis-after-success.sh

after_script:
  - sudo cat /var/log/upstart/docker.log
